import type { RegistryItem } from "@/types/registry";

// ============================================================================
// COMMUNITY PLUGINS (40 Total) - Imported from claude-code-plugins-plus
// Source: https://github.com/jeremylongshore/claude-code-plugins-plus
// Categories: DevOps, Security, Testing, Documentation, Data & Analytics
// ============================================================================

export const COMMUNITY_PLUGINS: RegistryItem[] = [
  // ============================================================================
  // DEVOPS & INFRASTRUCTURE (12 plugins)
  // ============================================================================
  {
    id: "community-terraform-state-analyzer",
    kind: "skill",
    name: "Terraform State Analyzer",
    slug: "terraform-state-analyzer",
    description:
      "Analyze Terraform state files for drift detection, resource dependencies, and cost optimization. 87% infrastructure accuracy.",
    longDescription:
      "Deep analysis of Terraform state files including drift detection between state and actual infrastructure, resource dependency mapping, cost estimation, and optimization recommendations. Identifies orphaned resources, circular dependencies, and security misconfigurations.",
    category: "DevOps & Infrastructure",
    tags: [
      "Terraform",
      "IaC",
      "Infrastructure",
      "State Management",
      "Cost Optimization",
    ],
    dependencies: [],
    files: [".claude/skills/terraform-state-analyzer/SKILL.md"],
    install: "npx @gicm/cli add skill/terraform-state-analyzer",
    tokenSavings: 85,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 75,
      status: "VERIFIED",
    },
  },
  {
    id: "community-helm-chart-generator",
    kind: "skill",
    name: "Helm Chart Generator",
    slug: "helm-chart-generator",
    description:
      "Generate production-ready Helm charts from existing deployments. Includes values templating and secrets management.",
    longDescription:
      "Automated Helm chart generation from Kubernetes deployments, StatefulSets, and Services. Creates values.yaml with environment-specific overrides, implements secrets management with sealed-secrets or external-secrets, and generates comprehensive NOTES.txt. Supports multi-environment deployments and GitOps workflows.",
    category: "DevOps & Infrastructure",
    tags: ["Helm", "Kubernetes", "Charts", "Deployment", "GitOps"],
    dependencies: ["kubernetes-patterns"],
    files: [".claude/skills/helm-chart-generator/SKILL.md"],
    install: "npx @gicm/cli add skill/helm-chart-generator",
    tokenSavings: 82,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 78,
      status: "VERIFIED",
    },
  },
  {
    id: "community-ansible-playbook-auditor",
    kind: "agent",
    name: "Ansible Playbook Auditor",
    slug: "ansible-playbook-auditor",
    description:
      "Audit Ansible playbooks for security, idempotency, and best practices. Detects hardcoded secrets and privilege escalation.",
    longDescription:
      "Comprehensive Ansible playbook security and quality auditing. Detects hardcoded passwords and API keys, checks for proper privilege escalation patterns, validates idempotency guarantees, identifies deprecated modules, and ensures role reusability. Generates remediation reports with specific line-by-line fixes.",
    category: "DevOps & Infrastructure",
    tags: [
      "Ansible",
      "Audit",
      "Security",
      "Configuration Management",
      "Automation",
    ],
    dependencies: [],
    files: [".claude/agents/ansible-playbook-auditor.md"],
    install: "npx @gicm/cli add agent/ansible-playbook-auditor",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 76,
      status: "VERIFIED",
    },
  },
  {
    id: "community-gitops-workflow-designer",
    kind: "agent",
    name: "GitOps Workflow Designer",
    slug: "gitops-workflow-designer",
    description:
      "Design GitOps workflows with ArgoCD/Flux. Implements progressive delivery, canary deployments, and rollback strategies.",
    longDescription:
      "End-to-end GitOps workflow design for Kubernetes environments. Creates ArgoCD Applications and ApplicationSets, Flux Kustomizations, progressive delivery with Argo Rollouts, canary analysis with Prometheus metrics, and automated rollback triggers. Includes multi-cluster sync strategies and drift detection.",
    category: "DevOps & Infrastructure",
    tags: ["GitOps", "ArgoCD", "Flux", "Kubernetes", "Progressive Delivery"],
    dependencies: ["kubernetes-patterns", "ci-cd-architect"],
    files: [".claude/agents/gitops-workflow-designer.md"],
    install: "npx @gicm/cli add agent/gitops-workflow-designer",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: ["ARGOCD_SERVER", "ARGOCD_AUTH_TOKEN"],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 80,
      status: "VERIFIED",
    },
  },
  {
    id: "community-pulumi-typescript-expert",
    kind: "skill",
    name: "Pulumi TypeScript Expert",
    slug: "pulumi-typescript-expert",
    description:
      "Infrastructure as Code with Pulumi and TypeScript. Type-safe cloud resources with full IDE support.",
    longDescription:
      "Advanced Pulumi patterns with TypeScript for AWS, GCP, Azure, and Kubernetes. Covers component resources, stack references, dynamic providers, policy-as-code with CrossGuard, and testing infrastructure with unit tests. Includes patterns for multi-cloud deployments and cost tagging.",
    category: "DevOps & Infrastructure",
    tags: ["Pulumi", "TypeScript", "IaC", "Multi-Cloud", "AWS", "GCP", "Azure"],
    dependencies: ["typescript-advanced-types"],
    files: [".claude/skills/pulumi-typescript-expert/SKILL.md"],
    install: "npx @gicm/cli add skill/pulumi-typescript-expert",
    tokenSavings: 84,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 77,
      status: "VERIFIED",
    },
  },
  {
    id: "community-incident-response-automation",
    kind: "agent",
    name: "Incident Response Automation",
    slug: "incident-response-automation",
    description:
      "Automate incident response with PagerDuty/Opsgenie integration. Runbook execution and escalation management.",
    longDescription:
      "Automated incident response workflows integrating with PagerDuty, Opsgenie, and Slack. Creates runbooks from incident post-mortems, implements automated remediation for known issues, manages escalation policies, and generates incident timelines. Includes Kubernetes pod restart automation and database failover scripts.",
    category: "DevOps & Infrastructure",
    tags: ["Incident Response", "PagerDuty", "Automation", "Runbooks", "SRE"],
    dependencies: ["monitoring-specialist"],
    files: [".claude/agents/incident-response-automation.md"],
    install: "npx @gicm/cli add agent/incident-response-automation",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: ["PAGERDUTY_API_KEY", "OPSGENIE_API_KEY", "SLACK_WEBHOOK_URL"],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 74,
      status: "VERIFIED",
    },
  },
  {
    id: "community-cost-optimization-advisor",
    kind: "agent",
    name: "Cloud Cost Optimization Advisor",
    slug: "cost-optimization-advisor",
    description:
      "Analyze cloud spend across AWS/GCP/Azure. Identify unused resources, rightsizing opportunities, and RI recommendations.",
    longDescription:
      "Multi-cloud cost optimization analysis covering AWS, GCP, and Azure. Identifies idle EC2/GCE instances, unused EBS volumes, oversized RDS instances, and underutilized load balancers. Provides Reserved Instance and Savings Plan recommendations, spot instance candidates, and auto-scaling improvements. Generates weekly cost reports with projected savings.",
    category: "DevOps & Infrastructure",
    tags: ["Cost Optimization", "FinOps", "AWS", "GCP", "Azure", "Cloud"],
    dependencies: [],
    files: [".claude/agents/cost-optimization-advisor.md"],
    install: "npx @gicm/cli add agent/cost-optimization-advisor",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 79,
      status: "VERIFIED",
    },
  },
  {
    id: "community-nginx-config-optimizer",
    kind: "skill",
    name: "Nginx Configuration Optimizer",
    slug: "nginx-config-optimizer",
    description:
      "Optimize Nginx configurations for performance, security, and caching. SSL/TLS hardening and rate limiting.",
    longDescription:
      "Production-grade Nginx configuration optimization including worker processes tuning, connection handling, gzip compression, static asset caching, SSL/TLS cipher suites (A+ rating), rate limiting patterns, and upstream load balancing. Generates configs for reverse proxy, API gateway, and static site hosting use cases.",
    category: "DevOps & Infrastructure",
    tags: ["Nginx", "Configuration", "Performance", "SSL", "Caching"],
    dependencies: [],
    files: [".claude/skills/nginx-config-optimizer/SKILL.md"],
    install: "npx @gicm/cli add skill/nginx-config-optimizer",
    tokenSavings: 80,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 81,
      status: "VERIFIED",
    },
  },
  {
    id: "community-docker-compose-production",
    kind: "skill",
    name: "Docker Compose Production Patterns",
    slug: "docker-compose-production",
    description:
      "Production-ready Docker Compose patterns. Health checks, resource limits, secrets management, and multi-stage builds.",
    longDescription:
      "Enterprise Docker Compose configurations with health checks, restart policies, resource constraints (CPU/memory limits), secrets and configs management, logging drivers, network isolation, and volume management. Includes patterns for local development, staging, and production environments with environment-specific overrides.",
    category: "DevOps & Infrastructure",
    tags: ["Docker", "Compose", "Production", "Containers", "DevOps"],
    dependencies: ["docker-containerization"],
    files: [".claude/skills/docker-compose-production/SKILL.md"],
    install: "npx @gicm/cli add skill/docker-compose-production",
    tokenSavings: 78,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 82,
      status: "VERIFIED",
    },
  },
  {
    id: "community-prometheus-alerting-rules",
    kind: "skill",
    name: "Prometheus Alerting Rules Designer",
    slug: "prometheus-alerting-rules",
    description:
      "Design Prometheus alerting rules with best practices. SLO-based alerts, runbook links, and alert fatigue prevention.",
    longDescription:
      "Production-grade Prometheus alerting rules following SRE best practices. Implements SLO-based alerting (error budgets, burn rates), multi-window multi-burn-rate alerts, symptom-based alerts over cause-based, and proper severity levels. Includes runbook link templates, alert inhibition rules, and Alertmanager routing configurations.",
    category: "DevOps & Infrastructure",
    tags: ["Prometheus", "Alerting", "SRE", "Monitoring", "SLO"],
    dependencies: ["monitoring-observability"],
    files: [".claude/skills/prometheus-alerting-rules/SKILL.md"],
    install: "npx @gicm/cli add skill/prometheus-alerting-rules",
    tokenSavings: 83,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 80,
      status: "VERIFIED",
    },
  },
  {
    id: "community-aws-cdk-patterns",
    kind: "skill",
    name: "AWS CDK Patterns Expert",
    slug: "aws-cdk-patterns",
    description:
      "Advanced AWS CDK patterns in TypeScript. L3 constructs, cross-stack references, and custom resources.",
    longDescription:
      "Expert-level AWS CDK patterns covering L3 construct development, cross-stack references with exports/imports, custom resources with Lambda, CDK Pipelines for CI/CD, aspect-based compliance checks, and CDK Nag security scanning. Includes patterns for serverless, ECS, and EKS deployments with proper IAM least-privilege.",
    category: "DevOps & Infrastructure",
    tags: ["AWS", "CDK", "TypeScript", "IaC", "Serverless", "ECS"],
    dependencies: ["typescript-advanced-types"],
    files: [".claude/skills/aws-cdk-patterns/SKILL.md"],
    install: "npx @gicm/cli add skill/aws-cdk-patterns",
    tokenSavings: 86,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 84,
      status: "VERIFIED",
    },
  },
  {
    id: "community-github-actions-matrix",
    kind: "skill",
    name: "GitHub Actions Matrix Strategies",
    slug: "github-actions-matrix",
    description:
      "Advanced GitHub Actions matrix builds. Dynamic matrices, conditional jobs, and reusable workflows.",
    longDescription:
      "Advanced GitHub Actions patterns for complex CI/CD pipelines. Covers dynamic matrix generation from JSON, conditional job execution with needs/if, reusable workflows with inputs/outputs, composite actions, environment protection rules, and OIDC authentication for cloud providers. Includes caching strategies and artifact management.",
    category: "DevOps & Infrastructure",
    tags: ["GitHub Actions", "CI/CD", "Matrix", "Workflows", "Automation"],
    dependencies: ["github-actions-workflows"],
    files: [".claude/skills/github-actions-matrix/SKILL.md"],
    install: "npx @gicm/cli add skill/github-actions-matrix",
    tokenSavings: 79,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 81,
      status: "VERIFIED",
    },
  },

  // ============================================================================
  // SECURITY & COMPLIANCE (10 plugins)
  // ============================================================================
  {
    id: "community-owasp-zap-integration",
    kind: "agent",
    name: "OWASP ZAP Security Scanner",
    slug: "owasp-zap-integration",
    description:
      "Automated OWASP ZAP security scanning integration. DAST for web applications with CI/CD pipeline support.",
    longDescription:
      "Dynamic Application Security Testing (DAST) integration with OWASP ZAP. Configures baseline scans, full scans, and API scans. Generates scan policies for specific vulnerability types, integrates with CI/CD pipelines via GitHub Actions/GitLab CI, and produces SARIF reports. Includes authentication handling for protected routes.",
    category: "Security & Compliance",
    tags: ["OWASP", "ZAP", "DAST", "Security Scanning", "Vulnerabilities"],
    dependencies: [],
    files: [".claude/agents/owasp-zap-integration.md"],
    install: "npx @gicm/cli add agent/owasp-zap-integration",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: ["ZAP_API_KEY"],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 82,
      status: "VERIFIED",
    },
  },
  {
    id: "community-soc2-compliance-checker",
    kind: "agent",
    name: "SOC 2 Compliance Checker",
    slug: "soc2-compliance-checker",
    description:
      "Verify SOC 2 compliance controls in codebase and infrastructure. Maps code to Trust Service Criteria.",
    longDescription:
      "Automated SOC 2 Type II compliance verification covering Security, Availability, Processing Integrity, Confidentiality, and Privacy criteria. Scans codebase for encryption at rest/transit, access controls, audit logging, data retention policies, and PII handling. Maps findings to specific SOC 2 control points and generates gap analysis reports.",
    category: "Security & Compliance",
    tags: ["SOC 2", "Compliance", "Audit", "Security", "Trust Services"],
    dependencies: [],
    files: [".claude/agents/soc2-compliance-checker.md"],
    install: "npx @gicm/cli add agent/soc2-compliance-checker",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 78,
      status: "VERIFIED",
    },
  },
  {
    id: "community-dependency-vulnerability-scanner",
    kind: "agent",
    name: "Dependency Vulnerability Scanner",
    slug: "dependency-vulnerability-scanner",
    description:
      "Scan npm/pip/cargo dependencies for CVEs. SBOM generation and license compliance checking.",
    longDescription:
      "Comprehensive dependency security analysis supporting npm, pip, cargo, go modules, and Maven. Generates SBOM in CycloneDX/SPDX formats, identifies CVEs with CVSS scores, checks license compliance against policy, and detects typosquatting attacks. Integrates with Snyk, Dependabot, and Renovate for automated remediation PRs.",
    category: "Security & Compliance",
    tags: ["Dependencies", "CVE", "SBOM", "License", "Vulnerabilities"],
    dependencies: [],
    files: [".claude/agents/dependency-vulnerability-scanner.md"],
    install: "npx @gicm/cli add agent/dependency-vulnerability-scanner",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: ["SNYK_TOKEN", "GITHUB_TOKEN"],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 85,
      status: "VERIFIED",
    },
  },
  {
    id: "community-gdpr-data-mapper",
    kind: "agent",
    name: "GDPR Data Flow Mapper",
    slug: "gdpr-data-mapper",
    description:
      "Map PII data flows for GDPR compliance. Identifies processing activities and data subject rights implementations.",
    longDescription:
      "Automated GDPR compliance analysis scanning codebase for PII collection, storage, and processing. Maps data flows to identify cross-border transfers, third-party processors, and retention periods. Verifies data subject rights implementations (access, erasure, portability), consent management, and lawful basis documentation. Generates Article 30 processing records.",
    category: "Security & Compliance",
    tags: ["GDPR", "Privacy", "PII", "Compliance", "Data Protection"],
    dependencies: [],
    files: [".claude/agents/gdpr-data-mapper.md"],
    install: "npx @gicm/cli add agent/gdpr-data-mapper",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 76,
      status: "VERIFIED",
    },
  },
  {
    id: "community-iac-security-scanner",
    kind: "skill",
    name: "IaC Security Scanner",
    slug: "iac-security-scanner",
    description:
      "Security scanning for Terraform, CloudFormation, and Kubernetes manifests. Checkov/tfsec integration.",
    longDescription:
      "Infrastructure as Code security analysis supporting Terraform, CloudFormation, Kubernetes YAML, Helm charts, and Dockerfiles. Integrates with Checkov, tfsec, kube-score, and trivy. Detects misconfigurations like public S3 buckets, overly permissive IAM policies, missing encryption, and insecure container configurations. Provides remediation code snippets.",
    category: "Security & Compliance",
    tags: ["IaC", "Security", "Terraform", "Kubernetes", "Checkov"],
    dependencies: ["terraform-infrastructure"],
    files: [".claude/skills/iac-security-scanner/SKILL.md"],
    install: "npx @gicm/cli add skill/iac-security-scanner",
    tokenSavings: 81,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 83,
      status: "VERIFIED",
    },
  },
  {
    id: "community-threat-modeling-assistant",
    kind: "agent",
    name: "Threat Modeling Assistant",
    slug: "threat-modeling-assistant",
    description:
      "STRIDE threat modeling for application architectures. Generate data flow diagrams and threat matrices.",
    longDescription:
      "Automated threat modeling using STRIDE methodology. Analyzes architecture diagrams and code to identify trust boundaries, data flows, and entry points. Generates threat matrices with attack vectors, likelihood, and impact scores. Creates data flow diagrams (DFD), proposes mitigations, and integrates with security issue trackers for threat tracking.",
    category: "Security & Compliance",
    tags: [
      "Threat Modeling",
      "STRIDE",
      "Security",
      "Architecture",
      "Risk Assessment",
    ],
    dependencies: [],
    files: [".claude/agents/threat-modeling-assistant.md"],
    install: "npx @gicm/cli add agent/threat-modeling-assistant",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 77,
      status: "VERIFIED",
    },
  },
  {
    id: "community-api-security-auditor",
    kind: "agent",
    name: "API Security Auditor",
    slug: "api-security-auditor",
    description:
      "Audit REST/GraphQL APIs for OWASP API Top 10 vulnerabilities. Rate limiting, auth, and injection checks.",
    longDescription:
      "Comprehensive API security auditing covering OWASP API Security Top 10. Tests for broken authentication, excessive data exposure, lack of rate limiting, injection vulnerabilities, improper inventory management, and mass assignment. Validates JWT implementation, API key security, CORS configuration, and GraphQL-specific issues (batching attacks, introspection exposure).",
    category: "Security & Compliance",
    tags: ["API Security", "OWASP", "REST", "GraphQL", "Authentication"],
    dependencies: [],
    files: [".claude/agents/api-security-auditor.md"],
    install: "npx @gicm/cli add agent/api-security-auditor",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 84,
      status: "VERIFIED",
    },
  },
  {
    id: "community-cryptography-advisor",
    kind: "skill",
    name: "Cryptography Best Practices Advisor",
    slug: "cryptography-advisor",
    description:
      "Implement cryptographic operations correctly. Key management, algorithm selection, and secure random generation.",
    longDescription:
      "Expert guidance on cryptographic implementations covering algorithm selection (AES-GCM, ChaCha20-Poly1305, RSA-OAEP), key derivation (PBKDF2, Argon2id, scrypt), secure random number generation, and proper initialization vector handling. Includes patterns for key rotation, envelope encryption, and integration with KMS services (AWS KMS, HashiCorp Vault, GCP KMS).",
    category: "Security & Compliance",
    tags: ["Cryptography", "Encryption", "Key Management", "Security", "KMS"],
    dependencies: [],
    files: [".claude/skills/cryptography-advisor/SKILL.md"],
    install: "npx @gicm/cli add skill/cryptography-advisor",
    tokenSavings: 86,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 88,
      status: "VERIFIED",
    },
  },
  {
    id: "community-container-hardening",
    kind: "skill",
    name: "Container Image Hardening",
    slug: "container-hardening",
    description:
      "Harden container images with distroless, non-root users, and minimal attack surface. Trivy scanning integration.",
    longDescription:
      "Container security hardening patterns including distroless base images, multi-stage builds for minimal images, non-root user execution, read-only filesystems, capability dropping, seccomp profiles, and AppArmor/SELinux policies. Integrates with Trivy, Snyk Container, and Docker Scout for vulnerability scanning. Includes Dockerfile linting with Hadolint.",
    category: "Security & Compliance",
    tags: ["Container Security", "Docker", "Hardening", "Trivy", "Distroless"],
    dependencies: ["docker-containerization", "container-security"],
    files: [".claude/skills/container-hardening/SKILL.md"],
    install: "npx @gicm/cli add skill/container-hardening",
    tokenSavings: 82,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 85,
      status: "VERIFIED",
    },
  },
  {
    id: "community-zero-trust-architecture",
    kind: "skill",
    name: "Zero Trust Architecture Patterns",
    slug: "zero-trust-architecture",
    description:
      "Implement Zero Trust security model. Identity verification, micro-segmentation, and least privilege access.",
    longDescription:
      "Zero Trust Network Architecture (ZTNA) implementation patterns covering identity-centric security, continuous verification, micro-segmentation with service mesh, mTLS everywhere, and context-aware access policies. Includes integration patterns for identity providers (Okta, Auth0, Azure AD), policy engines (OPA, Cedar), and secure service-to-service communication.",
    category: "Security & Compliance",
    tags: ["Zero Trust", "Security Architecture", "Identity", "mTLS", "ZTNA"],
    dependencies: ["authentication-patterns", "service-mesh-istio"],
    files: [".claude/skills/zero-trust-architecture/SKILL.md"],
    install: "npx @gicm/cli add skill/zero-trust-architecture",
    tokenSavings: 84,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 79,
      status: "VERIFIED",
    },
  },

  // ============================================================================
  // TESTING & QA (10 plugins)
  // ============================================================================
  {
    id: "community-contract-testing-pact",
    kind: "skill",
    name: "Contract Testing with Pact",
    slug: "contract-testing-pact",
    description:
      "Consumer-driven contract testing with Pact. API compatibility verification between services.",
    longDescription:
      "Consumer-driven contract testing using Pact for microservices. Covers Pact specification writing, provider verification, Pact Broker integration, pending pacts for safe breaking changes, and webhook-triggered verifications. Includes patterns for bi-directional contracts, message-based contracts, and GraphQL contract testing.",
    category: "Testing & QA",
    tags: [
      "Contract Testing",
      "Pact",
      "Microservices",
      "API Testing",
      "Integration",
    ],
    dependencies: [],
    files: [".claude/skills/contract-testing-pact/SKILL.md"],
    install: "npx @gicm/cli add skill/contract-testing-pact",
    tokenSavings: 80,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 78,
      status: "VERIFIED",
    },
  },
  {
    id: "community-mutation-testing",
    kind: "skill",
    name: "Mutation Testing Expert",
    slug: "mutation-testing",
    description:
      "Mutation testing with Stryker/PIT. Measure test suite effectiveness beyond code coverage.",
    longDescription:
      "Mutation testing implementation using Stryker (JavaScript/TypeScript), PIT (Java), and mutmut (Python). Explains mutation operators, survivor analysis, and test improvement strategies. Covers CI integration, incremental mutation testing for performance, and threshold configuration. Demonstrates how to achieve 80%+ mutation score.",
    category: "Testing & QA",
    tags: [
      "Mutation Testing",
      "Stryker",
      "Test Quality",
      "Code Coverage",
      "QA",
    ],
    dependencies: ["jest-unit-testing"],
    files: [".claude/skills/mutation-testing/SKILL.md"],
    install: "npx @gicm/cli add skill/mutation-testing",
    tokenSavings: 77,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 75,
      status: "VERIFIED",
    },
  },
  {
    id: "community-visual-regression-testing",
    kind: "skill",
    name: "Visual Regression Testing",
    slug: "visual-regression-testing",
    description:
      "Visual regression testing with Percy/Chromatic. Catch UI changes before production.",
    longDescription:
      "Visual regression testing setup with Percy, Chromatic, and BackstopJS. Covers Storybook integration for component snapshots, responsive breakpoint testing, dynamic content handling, and baseline management. Includes CI integration patterns, parallel snapshot capture, and threshold configuration for acceptable pixel differences.",
    category: "Testing & QA",
    tags: ["Visual Testing", "Percy", "Chromatic", "UI Testing", "Regression"],
    dependencies: ["playwright-e2e-testing"],
    files: [".claude/skills/visual-regression-testing/SKILL.md"],
    install: "npx @gicm/cli add skill/visual-regression-testing",
    tokenSavings: 79,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 80,
      status: "VERIFIED",
    },
  },
  {
    id: "community-chaos-engineering",
    kind: "agent",
    name: "Chaos Engineering Specialist",
    slug: "chaos-engineering",
    description:
      "Implement chaos experiments with LitmusChaos/Chaos Monkey. Validate system resilience under failure.",
    longDescription:
      "Chaos engineering implementation using LitmusChaos, Chaos Monkey, and Gremlin. Designs chaos experiments for pod failures, network partitions, CPU/memory stress, and database failovers. Covers steady-state hypothesis definition, blast radius control, automated rollback triggers, and gameday planning. Integrates with monitoring for experiment observation.",
    category: "Testing & QA",
    tags: [
      "Chaos Engineering",
      "LitmusChaos",
      "Resilience",
      "SRE",
      "Reliability",
    ],
    dependencies: ["kubernetes-patterns"],
    files: [".claude/agents/chaos-engineering.md"],
    install: "npx @gicm/cli add agent/chaos-engineering",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 76,
      status: "VERIFIED",
    },
  },
  {
    id: "community-api-test-generator",
    kind: "agent",
    name: "API Test Generator",
    slug: "api-test-generator",
    description:
      "Generate comprehensive API tests from OpenAPI specs. Positive, negative, and edge case scenarios.",
    longDescription:
      "Automated API test generation from OpenAPI/Swagger specifications. Creates positive path tests, negative tests (invalid inputs, missing fields), boundary value tests, authentication tests, and idempotency verification. Generates tests in Jest, Mocha, Pytest, or Postman Collection format. Includes test data generation with Faker.",
    category: "Testing & QA",
    tags: ["API Testing", "OpenAPI", "Test Generation", "Automation", "QA"],
    dependencies: [],
    files: [".claude/agents/api-test-generator.md"],
    install: "npx @gicm/cli add agent/api-test-generator",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 82,
      status: "VERIFIED",
    },
  },
  {
    id: "community-property-based-testing",
    kind: "skill",
    name: "Property-Based Testing Expert",
    slug: "property-based-testing",
    description:
      "Property-based testing with fast-check/Hypothesis. Generate hundreds of test cases from properties.",
    longDescription:
      "Property-based testing implementation using fast-check (JavaScript), Hypothesis (Python), and QuickCheck (Haskell-style). Defines properties (invariants, round-trip, metamorphic), creates custom generators/arbitraries, implements shrinking for minimal counterexamples, and integrates with existing test suites. Demonstrates testing mathematical properties, serialization, and state machines.",
    category: "Testing & QA",
    tags: [
      "Property Testing",
      "fast-check",
      "Hypothesis",
      "Test Generation",
      "QuickCheck",
    ],
    dependencies: ["jest-unit-testing"],
    files: [".claude/skills/property-based-testing/SKILL.md"],
    install: "npx @gicm/cli add skill/property-based-testing",
    tokenSavings: 81,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 79,
      status: "VERIFIED",
    },
  },
  {
    id: "community-accessibility-testing",
    kind: "agent",
    name: "Accessibility Testing Automation",
    slug: "accessibility-testing",
    description:
      "Automated WCAG 2.1 compliance testing. axe-core integration with detailed remediation guidance.",
    longDescription:
      "Automated accessibility testing for WCAG 2.1 AA/AAA compliance using axe-core, Pa11y, and Lighthouse. Tests for color contrast, keyboard navigation, ARIA attributes, focus management, and screen reader compatibility. Integrates with Playwright/Cypress for E2E accessibility testing. Generates detailed reports with WCAG criterion mapping and code-level fixes.",
    category: "Testing & QA",
    tags: ["Accessibility", "WCAG", "a11y", "axe-core", "Compliance"],
    dependencies: ["playwright-e2e-testing"],
    files: [".claude/agents/accessibility-testing.md"],
    install: "npx @gicm/cli add agent/accessibility-testing",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 83,
      status: "VERIFIED",
    },
  },
  {
    id: "community-database-test-fixtures",
    kind: "skill",
    name: "Database Test Fixtures Expert",
    slug: "database-test-fixtures",
    description:
      "Manage database test fixtures efficiently. Factory patterns, seeding, and isolation strategies.",
    longDescription:
      "Database test fixture management using factory patterns (FactoryBot-style), fixture files, and seeding scripts. Covers test isolation with transactions/truncation, foreign key handling, fixture composition for complex relationships, and performance optimization with fixture caching. Includes Prisma, TypeORM, and Sequelize specific patterns.",
    category: "Testing & QA",
    tags: ["Database", "Fixtures", "Testing", "Seeding", "Factories"],
    dependencies: ["jest-unit-testing"],
    files: [".claude/skills/database-test-fixtures/SKILL.md"],
    install: "npx @gicm/cli add skill/database-test-fixtures",
    tokenSavings: 76,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 77,
      status: "VERIFIED",
    },
  },
  {
    id: "community-test-data-management",
    kind: "agent",
    name: "Test Data Management Specialist",
    slug: "test-data-management",
    description:
      "Generate realistic test data at scale. PII masking, synthetic data, and GDPR-compliant testing.",
    longDescription:
      "Enterprise test data management covering synthetic data generation with Faker/Mimesis, PII detection and masking for production data copies, GDPR-compliant data subsetting, and referential integrity preservation. Includes data generation strategies for performance testing (millions of records), edge case data sets, and time-series data simulation.",
    category: "Testing & QA",
    tags: [
      "Test Data",
      "Synthetic Data",
      "PII Masking",
      "GDPR",
      "Data Generation",
    ],
    dependencies: [],
    files: [".claude/agents/test-data-management.md"],
    install: "npx @gicm/cli add agent/test-data-management",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 78,
      status: "VERIFIED",
    },
  },
  {
    id: "community-performance-test-design",
    kind: "skill",
    name: "Performance Test Design Patterns",
    slug: "performance-test-design",
    description:
      "Design effective performance tests. Load profiles, think times, and realistic user simulation.",
    longDescription:
      "Performance test design patterns covering load profile modeling (ramp-up, steady state, spike, soak), realistic think times, session handling, and correlation of dynamic values. Includes k6 script patterns, Gatling simulations, and JMeter test plans. Covers SLA-based assertions, percentile analysis, and bottleneck identification methodologies.",
    category: "Testing & QA",
    tags: [
      "Performance Testing",
      "Load Testing",
      "k6",
      "Gatling",
      "Test Design",
    ],
    dependencies: ["load-testing-k6"],
    files: [".claude/skills/performance-test-design/SKILL.md"],
    install: "npx @gicm/cli add skill/performance-test-design",
    tokenSavings: 83,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 81,
      status: "VERIFIED",
    },
  },

  // ============================================================================
  // DOCUMENTATION (4 plugins)
  // ============================================================================
  {
    id: "community-openapi-generator",
    kind: "agent",
    name: "OpenAPI Spec Generator",
    slug: "openapi-generator",
    description:
      "Generate OpenAPI 3.1 specs from code. Automatic endpoint discovery with rich examples.",
    longDescription:
      "Automated OpenAPI 3.1 specification generation from Express, Fastify, Next.js API routes, and NestJS controllers. Extracts route definitions, request/response schemas from Zod/Yup validators, generates realistic examples, and produces ReDoc/Swagger UI documentation. Includes schema component extraction and API versioning support.",
    category: "Documentation",
    tags: [
      "OpenAPI",
      "API Documentation",
      "Swagger",
      "ReDoc",
      "Spec Generation",
    ],
    dependencies: [],
    files: [".claude/agents/openapi-generator.md"],
    install: "npx @gicm/cli add agent/openapi-generator",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 84,
      status: "VERIFIED",
    },
  },
  {
    id: "community-adr-generator",
    kind: "agent",
    name: "Architecture Decision Record Generator",
    slug: "adr-generator",
    description:
      "Generate ADRs from technical discussions. MADR format with status tracking and supersession.",
    longDescription:
      "Architecture Decision Record generation following MADR (Markdown Architectural Decision Records) format. Captures context, decision drivers, considered options with pros/cons, decision outcome, and consequences. Tracks ADR lifecycle (proposed, accepted, deprecated, superseded) and maintains bidirectional links between related decisions. Includes templates for different decision types.",
    category: "Documentation",
    tags: ["ADR", "Architecture", "Documentation", "Decision Records", "MADR"],
    dependencies: [],
    files: [".claude/agents/adr-generator.md"],
    install: "npx @gicm/cli add agent/adr-generator",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 79,
      status: "VERIFIED",
    },
  },
  {
    id: "community-runbook-generator",
    kind: "agent",
    name: "Operations Runbook Generator",
    slug: "runbook-generator",
    description:
      "Generate operational runbooks from incident history. Step-by-step procedures with verification checks.",
    longDescription:
      "Operational runbook generation from incident post-mortems and system documentation. Creates step-by-step procedures with verification commands, rollback instructions, escalation paths, and estimated completion times. Supports both human-readable Markdown and machine-readable formats (for automation). Includes runbook testing guidance and version control integration.",
    category: "Documentation",
    tags: ["Runbooks", "Operations", "SRE", "Incident Response", "Procedures"],
    dependencies: [],
    files: [".claude/agents/runbook-generator.md"],
    install: "npx @gicm/cli add agent/runbook-generator",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 77,
      status: "VERIFIED",
    },
  },
  {
    id: "community-api-changelog-generator",
    kind: "agent",
    name: "API Changelog Generator",
    slug: "api-changelog-generator",
    description:
      "Generate API changelogs from OpenAPI diffs. Breaking changes detection with migration guides.",
    longDescription:
      "Automated API changelog generation by diffing OpenAPI specifications between versions. Categorizes changes as breaking (removed endpoints, required field additions), non-breaking (new endpoints, optional fields), and deprecations. Generates migration guides for breaking changes, produces changelog in Keep a Changelog format, and integrates with release workflows.",
    category: "Documentation",
    tags: ["API", "Changelog", "OpenAPI", "Versioning", "Breaking Changes"],
    dependencies: [],
    files: [".claude/agents/api-changelog-generator.md"],
    install: "npx @gicm/cli add agent/api-changelog-generator",
    layer: ".claude",
    modelRecommendation: "sonnet",
    envKeys: [],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 80,
      status: "VERIFIED",
    },
  },

  // ============================================================================
  // DATA & ANALYTICS (4 plugins)
  // ============================================================================
  {
    id: "community-data-pipeline-designer",
    kind: "agent",
    name: "Data Pipeline Designer",
    slug: "data-pipeline-designer",
    description:
      "Design ETL/ELT pipelines with Airflow/Dagster. Orchestration, backfills, and data quality checks.",
    longDescription:
      "Data pipeline architecture using Apache Airflow, Dagster, and Prefect. Designs DAGs with proper dependency management, implements idempotent tasks, handles backfills, and integrates data quality checks (Great Expectations, dbt tests). Covers partitioning strategies, incremental loads, and CDC patterns. Includes monitoring and alerting for pipeline health.",
    category: "Data & Analytics",
    tags: ["ETL", "Data Pipeline", "Airflow", "Dagster", "Orchestration"],
    dependencies: [],
    files: [".claude/agents/data-pipeline-designer.md"],
    install: "npx @gicm/cli add agent/data-pipeline-designer",
    layer: ".claude",
    modelRecommendation: "opus-4.5",
    envKeys: ["AIRFLOW_HOME"],
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 82,
      status: "VERIFIED",
    },
  },
  {
    id: "community-dbt-models-expert",
    kind: "skill",
    name: "dbt Models Expert",
    slug: "dbt-models-expert",
    description:
      "Build dbt models with best practices. Incremental models, testing, and documentation.",
    longDescription:
      "Expert dbt (data build tool) patterns covering model organization (staging, intermediate, marts), incremental models with merge strategies, snapshot (SCD Type 2) implementations, and reusable macros. Includes dbt testing (schema tests, data tests, unit tests), documentation generation, exposure definitions, and CI/CD integration with dbt Cloud or self-hosted.",
    category: "Data & Analytics",
    tags: [
      "dbt",
      "Data Modeling",
      "Analytics Engineering",
      "SQL",
      "Transformations",
    ],
    dependencies: ["sql-optimization"],
    files: [".claude/skills/dbt-models-expert/SKILL.md"],
    install: "npx @gicm/cli add skill/dbt-models-expert",
    tokenSavings: 85,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 86,
      status: "VERIFIED",
    },
  },
  {
    id: "community-data-visualization-expert",
    kind: "skill",
    name: "Data Visualization Expert",
    slug: "data-visualization-expert",
    description:
      "Create effective data visualizations. Chart selection, color theory, and accessibility considerations.",
    longDescription:
      "Data visualization best practices for dashboards and reports. Covers chart type selection based on data relationships, color theory for accessibility (colorblind-safe palettes), information hierarchy, and avoiding chartjunk. Implements visualizations with D3.js, Chart.js, Recharts, and Plotly. Includes dashboard layout patterns and responsive design for data-heavy UIs.",
    category: "Data & Analytics",
    tags: ["Data Visualization", "Charts", "D3.js", "Dashboards", "Analytics"],
    dependencies: [],
    files: [".claude/skills/data-visualization-expert/SKILL.md"],
    install: "npx @gicm/cli add skill/data-visualization-expert",
    tokenSavings: 78,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 80,
      status: "VERIFIED",
    },
  },
  {
    id: "community-streaming-analytics",
    kind: "skill",
    name: "Streaming Analytics Expert",
    slug: "streaming-analytics",
    description:
      "Real-time analytics with Kafka Streams/Flink. Windowing, aggregations, and exactly-once semantics.",
    longDescription:
      "Real-time streaming analytics implementation with Apache Kafka Streams, Apache Flink, and Apache Spark Structured Streaming. Covers windowing strategies (tumbling, sliding, session), stateful aggregations, late event handling, and exactly-once processing guarantees. Includes patterns for enrichment joins, deduplication, and real-time anomaly detection.",
    category: "Data & Analytics",
    tags: [
      "Streaming",
      "Kafka",
      "Flink",
      "Real-time Analytics",
      "Event Processing",
    ],
    dependencies: ["kafka-stream-processing"],
    files: [".claude/skills/streaming-analytics/SKILL.md"],
    install: "npx @gicm/cli add skill/streaming-analytics",
    tokenSavings: 84,
    installs: 0,
    remixes: 0,
    platforms: ["claude", "gemini", "openai"],
    compatibility: {
      models: [
        "opus-4.5",
        "sonnet-4.5",
        "sonnet",
        "gemini-2.0-flash",
        "gpt-4o",
      ],
      software: ["vscode", "cursor", "terminal", "windsurf"],
    },
    audit: {
      lastAudited: "2025-12-11",
      qualityScore: 81,
      status: "VERIFIED",
    },
  },
];

// Export helper to merge with main registry
export function getCommunityPlugins(): RegistryItem[] {
  return COMMUNITY_PLUGINS;
}

// Export category summary
export const COMMUNITY_PLUGIN_CATEGORIES = {
  "DevOps & Infrastructure": 12,
  "Security & Compliance": 10,
  "Testing & QA": 10,
  Documentation: 4,
  "Data & Analytics": 4,
  total: 40,
};
