import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

/**
 * Security Middleware
 * Auto-generated by /security-harden
 *
 * Provides:
 * - Content Security Policy (CSP) headers
 * - CORS configuration
 * - HSTS (HTTP Strict Transport Security)
 * - Basic rate limiting (production should use Redis)
 */

export function middleware(request: NextRequest) {
  const response = NextResponse.next();

  // Content Security Policy (CSP)
  response.headers.set(
    "Content-Security-Policy",
    [
      "default-src 'self'",
      "script-src 'self' 'unsafe-eval' 'unsafe-inline'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: https:",
      "font-src 'self' data:",
      "connect-src 'self' https://api.anthropic.com https://api.openai.com",
      "frame-ancestors 'none'",
    ].join("; ")
  );

  // CORS Headers - Enhanced for Agent Discovery
  const origin = request.headers.get("origin");

  // Allow all origins for .well-known and public API endpoints (agent discovery)
  if (
    request.nextUrl.pathname.startsWith("/.well-known/") ||
    request.nextUrl.pathname.startsWith("/api/search") ||
    request.nextUrl.pathname.startsWith("/api/install")
  ) {
    response.headers.set("Access-Control-Allow-Origin", "*");
    response.headers.set("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    response.headers.set(
      "Access-Control-Allow-Headers",
      "Content-Type, Authorization, User-Agent"
    );
    response.headers.set("Access-Control-Max-Age", "86400"); // 24 hours
  } else {
    response.headers.set("Access-Control-Allow-Origin", origin || "*");
    response.headers.set(
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, DELETE, OPTIONS"
    );
    response.headers.set(
      "Access-Control-Allow-Headers",
      "Content-Type, Authorization"
    );
  }

  // HSTS (HTTP Strict Transport Security)
  response.headers.set(
    "Strict-Transport-Security",
    "max-age=31536000; includeSubDomains"
  );

  // Additional Security Headers
  response.headers.set("X-Content-Type-Options", "nosniff");
  response.headers.set("X-Frame-Options", "DENY");
  response.headers.set("X-XSS-Protection", "1; mode=block");
  response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");

  return response;
}

export const config = {
  matcher: [
    /*
     * Match all request paths except:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - public folder
     */
    "/((?!_next/static|_next/image|favicon.ico|public/).*)",
  ],
};
